---
title: "Projektopgave, Positionsbestemmelse af enheder uden GPS dækning"

author: Søren Magnusson
author-meta: smag@tec.dk
affiliation: programmering, data teknikker, TEC
institute: programmering, data teknikker, TEC

date: 2025-11-30


format: 
  html: default
  typst: default
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
---
<!-- # Positionsbestemmelse af enheder uden GPS dækning -->

-   Hvordan laver man positionsbestemmelse af f.eks. mobile enheder, uden adgang til GPS?
-   Kan man tælle hvor mange enheder (og dermed måske personer), der er i et område?

Er man indendørs har man ofte ikke mulighed for at få en god positionsbestemmelse med GPS. I hvertfald ikke i metrosystemet, eller indenfor i et storcenter. Ikke på en måde så man tydeligt kan se hvor bygningen, eller i hvilket lokale, en person eller en enhed findes.\
Desuden kan man ønske at få oplysninger om hvormange (personer/enheder) der færdes i et område, uden at de har tilmeldt sig. Men må man det?

Hvordan kan man bestemme hvor en enhed befinder sig, uden at have adgang til GPS? Inde i bygninger er GPS signaler ikke særligt tilgængelige, og/eller særlige nøjagtige.

## Formål

I skal undersøge hvordan det er muligt at bestemme

-   om en enhed (mobiltelefon) er i området
-   hvor i området
-   hvor nøjagtigt

Samtidig skal I også forholde jer til

-   hvad det er tilladt at monitorere
-   om hvem
-   hvormeget, hvorlænge osv.

Undersøg hvordan man kan håndtere viden om enhederne så lidt som muligt, og alligevel registrere at der er enheder tilstede, hvor og hvornår.

## Produktmål

I skal lave en opstilling med flere IoT-enheder, som indsamler oplysninger om mobilenheder (f.eks.mobiltelefoner) med wifi.\
Det område I arbejder med kan være jeres bord eller hele lokalet.

Ved at placere flere IoT-enheder i hjørnerne af området, kan man få oplysninger om afstanden fra hver IoT-enhed til mobilenheden. På baggrund af disse oplysninger kan beregne geometrisk, hvor mobilenheden befinder sig. Nøjagtigheden bliver ikke så stor, men det må vi leve med.

I skal programmere IoT-enhederne i opstillingen til at kommunike med hinanden, så de kan samle oplysninger om afstand til mobilenheder, så der bliver mulighed for stedsbestemmelse. \
Skal en af IoT-enhederne være server, eller skal de alle samle data? Det er jeres valg.

Jeres opstalling af IoT-enheder skal indsende data til MQTT serveren (den som er sat op lokalt) med data om

-   et unikt id,
-   et tidspunkt, og
-   et kordinat (x,y)

En anden applikation (som ikke er indeholdt i denne opgave) kan så udtrække oplysningerne, og presentere statistiske sammendrag som hyppighed over dagen, et heatmap over hvor i området, osv

## Procesmål

Beskriv fremgangsmåde og teknologier der kan bruges til at nå målet.

Der er flere forskellige teknologier og strategier at vælge, og I skal lave noter om hvilke i har fundet oplysniger om, og lave forsøg med at implementere en eller flere. Implementerirngerne kan starte som nogle forsøg på hurtigt at se om det er muligt at bruge teknologien. Hvis det ikke er, kan man gå videre til noget andet. Hvis der er gode resultater, kan det bruges til at kombinere med flere.

Beskriv hvad I finder, hvad I prøver af, og hvordan den nye viden kan bruges.

Her er *logbog* og *portfolie* vigtige dokumentationsformer. I behøver *ikke* lave en traditionel rapport, bare i har ført *logbogen* og noteret i *portfoliet*. Helst undervejs.

## Hovedproblematikker

Der er et antal hovedproblematikker:

-   Triangulering
    -   Hvordan ser matematikken ud?
-   Afstand mellem målestation og mobil
    -   RSSI
        -   Kan findes med "sniffing" i wifi modulet promicius mode
    -   Roundtrip
-   Kommunikation mellem målestationer
    -   ESP MESH
    -   ESP NOW

### Persondata

Når vi indsamler data om alle enheder i "luften", så er nogen af disse data noget der har med perosner at gøre. Det gør at vi skal overveje hvordan vi behandler disse oplysninger. Projektet kommer muligvis i berøring med Persondata lovgivningen, som igen refererer til EUs GDPR.

-   Hvilke disse data er personlige?
    -   Er de følsomme?
    -   Hele tiden, eller nogen gange?
    -   Er f.eks. en MAC-adresse følsom personlig data?
-   Beriges data ved at indsamle f.eks. MAC adressse, sammen med tid og sted?
    -   Hvad gør det ved data-ansvaret?
-   Kan vi begrænse hvilke oplysninger der opsamles, i forhold til formålet?

## Aflevering 

Opgaven skal afleveres på ItsLearning (man kan ikke lave ekseterne links ind). /
I skal aflevere alle kode filer (naturligvis), samt logbog og arbejdsportefolie.
Enten skal det hele pakkes i en komprimeret fil (f.eks. zip), eller hvis I har projektet i git og på GitLab, GitHub eller lignende, så er det fint at I bare afleverer et link til repo'et. Husk bare at læreren skal have læse rettigheder (eller bare public).

### Tidlig aflevering

Hvis projektet alligevel ligger på et offentligt git repo (eller noget lignende), kan i godt lave en tidlig aflevering, og så løbende pushe til repo'et. På den måde kan læreren følge med i logbog og portefolie.

## Spørgsmål som indgår i bedømmelsen

Opgavens karakter er udpræget eksplorativ. Det vil sige at I skal undersøge hvad og hvordan det kan lade sig gøre. Så undesøgelsen tæller i sig selv. Det tæller også at kode noget. Så altså begge dele.

-   [ ] Hvordan ser løsningen ud
    -   [ ] Arkitektur
    -   [ ] Teknologier
-   [ ] Dataprocess
    -   [ ] primær dataopsamling
    -   [ ] data berigelse
    -   [ ] beregning
    -   [ ] data lagring
    -   [ ] evt data visualisering
-   [ ] Datasikkerhed
    -   [ ] Følsomhed
        -   [ ] hvad er personlige data?
        -   [ ] hvad er risikoen ved at behandle andre folks personlige data?
        -   [ ] i hvor høj grad er de data projektet benytter personlige?
            -   [ ] er data mere personlige når de beriges?
        -   [ ] hvor længe er der brug for at have personlige data i projektet?
    -   [ ] Beskyttelse
        -   [ ] hvem kan få adgang?
        -   [ ] hvor svært er det for udenforstående at skaffe sig adgang til data?
        -   [ ] eller at lytte med?

## Forslag til teknologier at kigge på

1.  prøv først med at opsamle RSSI ved at lytte til net pakker, i promiscuis mode
2.  prøv at lave en tilnærmet afstandsberegning
3.  undersøg hvordan afstand/RSSI kan udveklses mellem ESP32-enhederne
    1.  Kan man bruge ESP-MESH mens enheden sniffer?
    2.  Kan man bruge ESP-NOW?
        -   Kan det sikres/krypteres
4.  Med afstand/signalstyrke/RSSI fra flere stationer, Hvordan kan man så beregne (men tilnærmet nøjagtighed), hvor mobilen befinder sig?

### Links

#### Generelt

-   <https://www.bitbrain.com/blog/indoor-positioning-system>

#### Math

-   <https://link.springer.com/article/10.1186/s13673-020-00236-8>

#### Persondata og GDPR

-   <https://pentests.dk/docs/gdpr-developers-guide/>
    -   Original (på engelsk) <https://github.com/LINCnil/GDPR-Developer-Guide>

### Kode eksempler

#### WiFi sniffter

-   En demo af en wifi sniffer lavet med generativ AI (Claude). [demo_kode/Proximity sniffer](https://github.com/s0ren/IndoorPos_opgave_noter/tree/main/demo_kode/Proximity%20sniffer)

-   og lidt flere på <https://github.com/s0ren/IndoorPos_opgave_noter>

-   en anden wifi sniffer <https://github.com/ETS-PoliTO/esp32-sniffer>

### MQTT server

Der er opstillet en lokal MQTT server i undervisningslokalet, som i skal bruge. Under udviklingen kan i godt gøre brug af jeres egen.

Se: [Lokal MQTT server](../Features/lokal_mqtt.qmd)

<!--
#### MQTT & MongoDB server setup

Et docker-compose projekt som kører Mosquitto MQTT og MongoDB, samt en tilhørende mqtt-subscriber, til at overføre fra MQTT til mongoDB. Se mappen [demo_kode/mqtt_mongdb_server/](/demo_kode/mqtt_mongdb_server/).
-->